// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 mailbox.gltf
// Author: Jens (https://sketchfab.com/excitedneon)
// License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
// Source: https://sketchfab.com/3d-models/30days3d-day-3-mail-box-357acbf2a0d04aa591a7d71982af0436
// Title: #30Days3D - Day 3 - Mail Box
// */

// import React from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";
// import * as THREE from "three";

// type GLTFResult = GLTF & {
//   nodes: {
//     Mailbox_0: THREE.Mesh;
//     Mailbox_1: THREE.Mesh;
//     Letters_0: THREE.Mesh;
//   };
//   materials: {
//     Red_Metal: THREE.MeshStandardMaterial;
//     Gray_Metal: THREE.MeshStandardMaterial;
//     Paper: THREE.MeshStandardMaterial;
//   };
// };

// type ModelProps = JSX.IntrinsicElements["group"];

// export default function Model(props: ModelProps) {
//   const { nodes, materials } = useGLTF<GLTFResult>("/mailbox.gltf");

//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh
//           geometry={nodes.Mailbox_0.geometry}
//           material={materials.Red_Metal}
//         />
//         <mesh
//           geometry={nodes.Mailbox_1.geometry}
//           material={materials.Gray_Metal}
//         />
//         <mesh geometry={nodes.Letters_0.geometry} material={materials.Paper} />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/mailbox.gltf");
